/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.31
 * Generated at: 2024-11-04 08:29:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import javaweb.model.dto.ProductDto;
import java.util.List;

public final class product_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.0.jar", Long.valueOf(1730254456175L));
    _jspx_dependants.put("/WEB-INF/view/menu.jspf", Long.valueOf(1730708925388L));
    _jspx_dependants.put("jar:file:/D:/JavaClass/WorkSpace/Lab/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/javaweb/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.0.jar!/META-INF/fmt.tld", Long.valueOf(1649407098000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("javaweb.model.dto.ProductDto");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!-- 格式化庫 -->\r\n");
      out.write("\r\n");

	// 得到 ProductServlet 所傳來的資料
	List<ProductDto> productDtos = (List<ProductDto>)request.getAttribute("productDtos");

      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<title>Product</title>\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/purecss@3.0.0/build/pure-min.css\">\r\n");
      out.write("		<style>\r\n");
      out.write("        .button-success,\r\n");
      out.write("        .button-error,\r\n");
      out.write("        .button-warning,\r\n");
      out.write("        .button-secondary {\r\n");
      out.write("            color: white;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            text-shadow: 0 1px 1px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button-success {\r\n");
      out.write("            background: rgb(28, 184, 65);\r\n");
      out.write("            /* this is a green */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button-error {\r\n");
      out.write("            background: rgb(202, 60, 60);\r\n");
      out.write("            /* this is a maroon */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button-warning {\r\n");
      out.write("            background: rgb(223, 117, 20);\r\n");
      out.write("            /* this is an orange */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button-secondary {\r\n");
      out.write("            background: rgb(66, 184, 221);\r\n");
      out.write("            /* this is a light blue */\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("	</head>\r\n");
      out.write("	\r\n");
      out.write("	<body style=\"padding: 20px\">\r\n");
      out.write("		<!-- menu bar include -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<div class=\"pure-menu pure-menu-horizontal\" style=\"background-color: #dddddd;height: 50px; align-content: center;\">\r\n");
      out.write("	<!-- menu bar -->\r\n");
      out.write("	<a href=\"/javaweb/users\" class=\"pure-menu-heading pure-menu-link\">使用者維護檔</a>\r\n");
      out.write("	<a href=\"/javaweb/login\" class=\"pure-menu-heading pure-menu-link\">登入</a>\r\n");
      out.write("	<a href=\"/javaweb/user/update/password\" class=\"pure-menu-heading pure-menu-link\">修改密碼</a>\r\n");
      out.write("	<a href=\"/javaweb/products\" class=\"pure-menu-heading pure-menu-link\">商品維護檔</a>\r\n");
      out.write("	<a href=\"/javaweb/order\" class=\"pure-menu-heading pure-menu-link\">訂購商品</a>\r\n");
      out.write("	<a href=\"/javaweb/cart\" class=\"pure-menu-heading pure-menu-link\">購物車( 結帳, 取消 )</a>\r\n");
      out.write("	<a href=\"/javaweb/order/history\" class=\"pure-menu-heading pure-menu-link\">歷史訂單</a>\r\n");
      out.write("	<a href=\"/javaweb/product/sales/ranking\" class=\"pure-menu-heading pure-menu-link\">銷售排行</a>\r\n");
      out.write("	<a href=\"/javaweb/logout\" class=\"pure-menu-heading pure-menu-link\" >登出</a>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("		<form class=\"pure-form\" method=\"post\" action=\"/javaweb/product/add\">\r\n");
      out.write("				<fieldset>\r\n");
      out.write("					<legend>Product 新增</legend>\r\n");
      out.write("					產品名稱: <input type=\"text\" name=\"productname\" placeholder=\"請輸入產品名稱\" required /><p /> \r\n");
      out.write("					產品價格: <input type=\"text\" name=\"productprice\" placeholder=\"請輸入產品價格\" required /><p /> \r\n");
      out.write("					產品庫存: <input type=\"text\" name=\"stockquantity\" placeholder=\"請輸入產品庫存量\" required /><p />\r\n");
      out.write("					<button class=\"pure-button\" type=\"reset\">Reset</button>\r\n");
      out.write("					<button class=\"button-success pure-button\" type=\"submit\">Submit</button>	  \r\n");
      out.write("				</fieldset>\r\n");
      out.write("		</form>\r\n");
      out.write("		<p />\r\n");
      out.write("	\r\n");
      out.write("		<div>\r\n");
      out.write("			<fieldset>\r\n");
      out.write("				<legend>Product 列表</legend>\r\n");
      out.write("				<table border=\"1\" class=\"pure-table\">\r\n");
      out.write("					<thead>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>商品ID</th><th>產品名稱</th><th>商品價格</th><th>產品庫存量</th>\r\n");
      out.write("							<th>刪除</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("					");
 for(ProductDto productDto : productDtos) { 
      out.write("\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>");
      out.print(productDto.getProductId() );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(productDto.getProductname() );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(productDto.getPrice() );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(productDto.getStockquantity() );
      out.write("</td>\r\n");
      out.write("							<td><a href=\"http://localhost:8080/javaweb/product/delete?productId=");
      out.print(productDto.getProductId() );
      out.write("\" class=\"button-error pure-button\">刪除</a></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("				</table>\r\n");
      out.write("			</fieldset>\r\n");
      out.write("		</div>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
